### ISSUE TITLE
Feature request:  xxhash support 

### ISSUE THREAD

**Issue by yzcj105** [Glavo/gchecksum#3]
I wonder if the author has considered adding xxhash as a choice. It would be much faster for huge files. The throughout is limited by the IO rather than cpu. 

xxhash is a very fast algorithm, which supports parallelization. 

See Also 
[xxhash](https://github.com/Cyan4973/xxHash)

**Comment by Glavo** [comment]
gchecksum 0.12.0 has been released, which includes experimental support for xxHash64. (Surprisingly, gchecksum is 35% faster than `xxh64sum`)

Support for xxHash3 is still under development. I am busy with other things recently, so I can't finish it for the time being.

**Comment by yzcj105** [comment]
Thank you very much!  It has been really powerful so far and very convenient to use.   Before using gchecksum, I use find --exec and xxhsum to generate checksum files, it has been very slow. However, if I use `tar cf - <dir> | xxhsum` it would be much faster. I suppose the bottleneck is find command, or maybe it didn't overlap IO and cpu computation.

**Comment by yzcj105** [comment]
xxh works very fast with large file, almost reach the hard drive maximum speed with low cpu usage.

**Comment by Glavo** [comment]
gchecksum 0.13.0 has been released, which includes experimental support for XXH128 (XXH3 128bits).

I added unit tests and also tested with some real files. But unit tests also have limitations so I can't guarantee it will be correct for all inputs, so I left it experimental for now.

(Note: I observed that gchecksum and xxh128sum get different hashes for some files, the reason is that XXH3 is not stable before xxHash 0.8.0, so please do not use the old version of xxhsum)

Due to my limited time, I will not add support for XXH32 and XXH3 64bits for the time being. I'll probably implement them after I have a way to adequately test the correctness of the hashing algorithm.

**Comment by Glavo** [comment]
I have updated the [benchmark results](https://github.com/Glavo/gchecksum#benchmark), and I think it should be helpful for users.
